services:
  nginx:
    image: nginx:alpine
    container_name: budgetmate-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./landing/public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]
