services:
  nginx:
    build:
      context: ./budgetmate-v2-app
      dockerfile: Dockerfile
    container_name: budgetmate-nginx
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./budgetmate-v2-app/landing/public:/usr/share/nginx/html:ro
      - ./budgetmate-v2-app/nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - frontend

  api:
    build:
      context: ./budgetmate-v2-api
    container_name: budgetmate-api
    restart: unless-stopped
    env_file:
      - ./budgetmate-v2-api/.env
    depends_on:
      - db
    ports:
      - "8089:8080"
    networks:
      - backend
      - frontend

  db:
    image: postgres:alpine
    container_name: budgetmate-db
    restart: unless-stopped
    env_file:
      - ./budgetmate-v2-api/.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./budgetmate-v2-api/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
  frontend: