### Get user accounts.
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {Array<{"id", "name", "currency", "currentBalance", "type", "avatarColor"}>}
GET http://localhost:8089/api/v3/accounts HTTP/1.1
Accept: application/json;

### Add user account.
# Expected response status => HTTP/1.1 201
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "name", "currency", "currentBalance", "type", "avatarColor"}}
POST http://localhost:8089/api/v3/accounts HTTP/1.1
Accept: application/json;
Content-Type: application/json;charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGJ1ZGdldG1hdGUuY29tIiwiaWF0IjoxNzU1NTI0NjA0LCJleHAiOjE3NTU1MzU0MDR9.ERQ3YCp7JqQCK6ockRTU5gS7sFDqo-y_8KhNz5hjnKo

{
  "name": "Account-Test",
  "currency": "USD",
  "currentBalance": 27070,
  "type": "CASH"
}


### Get user accout.
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "name", "currency", "currentBalance", "type", "avatarColor"}}
GET http://localhost:8089/api/v3/accounts/33d114b6-75f9-4832-9730-ffadab2f54ef HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGJ1ZGdldG1hdGUuY29tIiwiaWF0IjoxNzU1NTI0NjA0LCJleHAiOjE3NTU1MzU0MDR9.ERQ3YCp7JqQCK6ockRTU5gS7sFDqo-y_8KhNz5hjnKo


### Update user account.
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "name", "currency", "currentBalance", "type", "avatarColor"}}
PATCH http://localhost:8089/api/v3/accounts/33d114b6-75f9-4832-9730-ffadab2f54ef HTTP/1.1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGJ1ZGdldG1hdGUuY29tIiwiaWF0IjoxNzU1NTI0NjA0LCJleHAiOjE3NTU1MzU0MDR9.ERQ3YCp7JqQCK6ockRTU5gS7sFDqo-y_8KhNz5hjnKo

{
  "type": "CREDIT_CARD",
  "currentBalance": 27000
}


### Delete user account.
# Expected response status => HTTP/1.1 204
# Expected response content type => Content-Type: application/json
# Expected response body => Empty
DELETE http://localhost:8089/api/v3/accounts/33d114b6-75f9-4832-9730-ffadab2f54ef HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGJ1ZGdldG1hdGUuY29tIiwiaWF0IjoxNzU1NTI0NjA0LCJleHAiOjE3NTU1MzU0MDR9.ERQ3YCp7JqQCK6ockRTU5gS7sFDqo-y_8KhNz5hjnKo
