### Add user account request.
POST http://localhost:8089/api/v1/account-requests HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb2JlcnRzYXJnc3lhbjI3QGdtYWlsLmNvbSIsImlhdCI6MTc1NTUxMzMyMiwiZXhwIjoxNzU1NTI0MTIyfQ.wUO5KnHlIvsOF2vwg4NEZ6Uu6UXqlOxkR_CzOoxZfEE

{
  "accountName": "General Account",
  "ownerUsername": "user@budgetmate.com"
}


### Update user account request.
PATCH http://localhost:8089/api/v1/account-requests/257b0760-24ce-46a1-ace0-b442657790ce HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGJ1ZGdldG1hdGUuY29tIiwiaWF0IjoxNzU1NTEzMzcwLCJleHAiOjE3NTU1MjQxNzB9.eT9JDzKEEQs1k3pmWiNzAvqohrsTgMmt-bELPP763NI

{
  "status": true
}
