### Get user accounts.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {Array<{"id", "name", "currency", "currentBalance", "type", "avatarColor"}>}
GET http://localhost:8089/api/v3/accounts HTTP/1.1
Accept: application/json;
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}; XSRF-TOKEN=33203290-caef-4c60-bc24-812cef7c6828
X-XSRF-TOKEN: AjbaL-Ej5pqav4MOAAWTQ5mr0sgTwiObPGjAQlBO1ZZC-wNNMQXoH9IR36q33OJrZiinIK-b_6pw8Be2BFnyITUo4vV0wzF1


### Add user account.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 201
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "name", "currency", "currentBalance", "type", "avatarColor"}}
POST http://localhost:8089/api/v3/accounts HTTP/1.1
Accept: application/json;
Content-Type: application/json;charset=UTF-8
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}; XSRF-TOKEN=33203290-caef-4c60-bc24-812cef7c6828
X-XSRF-TOKEN: AjbaL-Ej5pqav4MOAAWTQ5mr0sgTwiObPGjAQlBO1ZZC-wNNMQXoH9IR36q33OJrZiinIK-b_6pw8Be2BFnyITUo4vV0wzF1

{
  "name": "Account-Test",
  "currency": "USD",
  "currentBalance": 27070,
  "type": "CASH"
}


### Get user accout.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "name", "currency", "currentBalance", "type", "avatarColor"}}
GET http://localhost:8089/api/v3/accounts/33d114b6-75f9-4832-9730-ffadab2f54ef HTTP/1.1
Accept: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}; XSRF-TOKEN=33203290-caef-4c60-bc24-812cef7c6828
X-XSRF-TOKEN: AjbaL-Ej5pqav4MOAAWTQ5mr0sgTwiObPGjAQlBO1ZZC-wNNMQXoH9IR36q33OJrZiinIK-b_6pw8Be2BFnyITUo4vV0wzF1


### Update user account.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "name", "currency", "currentBalance", "type", "avatarColor"}}
PATCH http://localhost:8089/api/v3/accounts/33d114b6-75f9-4832-9730-ffadab2f54ef HTTP/1.1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}; XSRF-TOKEN=33203290-caef-4c60-bc24-812cef7c6828
X-XSRF-TOKEN: AjbaL-Ej5pqav4MOAAWTQ5mr0sgTwiObPGjAQlBO1ZZC-wNNMQXoH9IR36q33OJrZiinIK-b_6pw8Be2BFnyITUo4vV0wzF1

{
  "type": "CREDIT_CARD",
  "currentBalance": 27000
}


### Delete user account.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 204
# Expected response content type => Content-Type: application/json
# Expected response body => Empty
DELETE http://localhost:8089/api/v3/accounts/33d114b6-75f9-4832-9730-ffadab2f54ef HTTP/1.1
Accept: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}; XSRF-TOKEN=33203290-caef-4c60-bc24-812cef7c6828
X-XSRF-TOKEN: AjbaL-Ej5pqav4MOAAWTQ5mr0sgTwiObPGjAQlBO1ZZC-wNNMQXoH9IR36q33OJrZiinIK-b_6pw8Be2BFnyITUo4vV0wzF1
