### Add user account request.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 201
# Expected response content type => Content-Type: application/json
# Expected response body => {{ "id", "ownerUsername", "requestedUsername", "accountName" }}
POST http://localhost:8089/api/v1/account-requests HTTP/1.1
Accept: application/json
Content-Type: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}

{
  "accountName": "General Account",
  "ownerUsername": "user1@budgetmate.com"
}


### Update user account request.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {{ "id", "ownerUsername", "requestedUsername", "accountName" }}
PATCH http://localhost:8089/api/v1/account-requests/257b0760-24ce-46a1-ace0-b442657790ce HTTP/1.1
Accept: application/json
Content-Type: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}

{
  "status": true
}
