### Get user budgets.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {Array<{"id", "name", "amount", "userId", "recordCategories"}>}
GET http://localhost:8089/api/v3/budgets HTTP/1.1
Accept: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}; XSRF-TOKEN=33203290-caef-4c60-bc24-812cef7c6828
X-XSRF-TOKEN: AjbaL-Ej5pqav4MOAAWTQ5mr0sgTwiObPGjAQlBO1ZZC-wNNMQXoH9IR36q33OJrZiinIK-b_6pw8Be2BFnyITUo4vV0wzF1


### Add user budget.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 201
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "name", "amount", "userId", "recordCategories"}}
POST http://localhost:8089/api/v3/budgets HTTP/1.1
Accept: application/json
Content-Type: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}; XSRF-TOKEN=33203290-caef-4c60-bc24-812cef7c6828
X-XSRF-TOKEN: AjbaL-Ej5pqav4MOAAWTQ5mr0sgTwiObPGjAQlBO1ZZC-wNNMQXoH9IR36q33OJrZiinIK-b_6pw8Be2BFnyITUo4vV0wzF1

{
  "name": "Budget-Test",
  "amount": 17000,
  "recordCategories": ["Rent", "Insurance"]
}


### Get user budgets current balance.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {Array<{"id", "currentBalance"}>}
GET http://localhost:8089/api/v3/budgets/current-balance HTTP/1.1
Accept: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}; XSRF-TOKEN=33203290-caef-4c60-bc24-812cef7c6828
X-XSRF-TOKEN: AjbaL-Ej5pqav4MOAAWTQ5mr0sgTwiObPGjAQlBO1ZZC-wNNMQXoH9IR36q33OJrZiinIK-b_6pw8Be2BFnyITUo4vV0wzF1


### Get user budgets report.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response content disposition => Content-Disposition: attachment; filename=budgets-report.json
# Expected response body => {Array<{"id", "name", "amount", "userId", "recordCategories"}>}
GET http://localhost:8089/api/v3/budgets/report HTTP/1.1
Accept: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}; XSRF-TOKEN=33203290-caef-4c60-bc24-812cef7c6828
X-XSRF-TOKEN: AjbaL-Ej5pqav4MOAAWTQ5mr0sgTwiObPGjAQlBO1ZZC-wNNMQXoH9IR36q33OJrZiinIK-b_6pw8Be2BFnyITUo4vV0wzF1


### Get user budget.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "name", "amount", "userId", "recordCategories"}}
GET http://localhost:8089/api/v3/budgets/d8652531-fb8b-49a8-8880-c73115060e9a HTTP/1.1
Accept: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}; XSRF-TOKEN=33203290-caef-4c60-bc24-812cef7c6828
X-XSRF-TOKEN: AjbaL-Ej5pqav4MOAAWTQ5mr0sgTwiObPGjAQlBO1ZZC-wNNMQXoH9IR36q33OJrZiinIK-b_6pw8Be2BFnyITUo4vV0wzF1


### Update user budget.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "name", "amount", "userId", "recordCategories"}}
PATCH http://localhost:8089/api/v3/budgets/d8652531-fb8b-49a8-8880-c73115060e9a HTTP/1.1
Accept: application/json
Content-Type: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}; XSRF-TOKEN=33203290-caef-4c60-bc24-812cef7c6828
X-XSRF-TOKEN: AjbaL-Ej5pqav4MOAAWTQ5mr0sgTwiObPGjAQlBO1ZZC-wNNMQXoH9IR36q33OJrZiinIK-b_6pw8Be2BFnyITUo4vV0wzF1

{
  "name": "Budget-Test-2",
  "amount": 17500,
  "recordCategories": ["Grocery"]
}


### Delete user budget.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 204
# Expected response content type => Content-Type: application/json
# Expected response body => Empty
DELETE http://localhost:8089/api/v3/budgets/d8652531-fb8b-49a8-8880-c73115060e9a HTTP/1.1
Accept: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}; XSRF-TOKEN=33203290-caef-4c60-bc24-812cef7c6828
X-XSRF-TOKEN: AjbaL-Ej5pqav4MOAAWTQ5mr0sgTwiObPGjAQlBO1ZZC-wNNMQXoH9IR36q33OJrZiinIK-b_6pw8Be2BFnyITUo4vV0wzF1