### Get user budgets.
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {Array<{"id", "name", "amount", "userId", "recordCategories"}>}
GET http://localhost:8089/api/v3/budgets HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGJ1ZGdldG1hdGUuY29tIiwiaWF0IjoxNzU1NTI0NjA0LCJleHAiOjE3NTU1MzU0MDR9.ERQ3YCp7JqQCK6ockRTU5gS7sFDqo-y_8KhNz5hjnKo


### Add user budget.
# Expected response status => HTTP/1.1 201
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "name", "amount", "userId", "recordCategories"}}
POST http://localhost:8089/api/v3/budgets HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGJ1ZGdldG1hdGUuY29tIiwiaWF0IjoxNzU1NTI0NjA0LCJleHAiOjE3NTU1MzU0MDR9.ERQ3YCp7JqQCK6ockRTU5gS7sFDqo-y_8KhNz5hjnKo

{
  "name": "Budget-Test",
  "amount": 17000,
  "recordCategories": ["Rent", "Insurance"]
}


### Get user budgets current balance.
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {Array<{"id", "currentBalance"}>}
GET http://localhost:8089/api/v3/budgets/current-balance HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGJ1ZGdldG1hdGUuY29tIiwiaWF0IjoxNzU1NTI0NjA0LCJleHAiOjE3NTU1MzU0MDR9.ERQ3YCp7JqQCK6ockRTU5gS7sFDqo-y_8KhNz5hjnKo


### Get user budgets report.
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response content disposition => Content-Disposition: attachment; filename=budgets-report.json
# Expected response body => {Array<{"id", "name", "amount", "userId", "recordCategories"}>}
GET http://localhost:8089/api/v3/budgets/report HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGJ1ZGdldG1hdGUuY29tIiwiaWF0IjoxNzU1NTI0NjA0LCJleHAiOjE3NTU1MzU0MDR9.ERQ3YCp7JqQCK6ockRTU5gS7sFDqo-y_8KhNz5hjnKo


### Get user budget.
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "name", "amount", "userId", "recordCategories"}}
GET http://localhost:8089/api/v3/budgets/d8652531-fb8b-49a8-8880-c73115060e9a HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGJ1ZGdldG1hdGUuY29tIiwiaWF0IjoxNzU1NTI0NjA0LCJleHAiOjE3NTU1MzU0MDR9.ERQ3YCp7JqQCK6ockRTU5gS7sFDqo-y_8KhNz5hjnKo


### Update user budget.
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "name", "amount", "userId", "recordCategories"}}
PATCH http://localhost:8089/api/v3/budgets/d8652531-fb8b-49a8-8880-c73115060e9a HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGJ1ZGdldG1hdGUuY29tIiwiaWF0IjoxNzU1NTI0NjA0LCJleHAiOjE3NTU1MzU0MDR9.ERQ3YCp7JqQCK6ockRTU5gS7sFDqo-y_8KhNz5hjnKo

{
  "name": "Budget-Test-2",
  "amount": 17500,
  "recordCategories": ["Grocery"]
}


### Delete user budget.
# Expected response status => HTTP/1.1 204
# Expected response content type => Content-Type: application/json
# Expected response body => Empty
DELETE http://localhost:8089/api/v3/budgets/d8652531-fb8b-49a8-8880-c73115060e9a HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGJ1ZGdldG1hdGUuY29tIiwiaWF0IjoxNzU1NTI0NjA0LCJleHAiOjE3NTU1MzU0MDR9.ERQ3YCp7JqQCK6ockRTU5gS7sFDqo-y_8KhNz5hjnKo