### Search user records.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {Array<{"id", "amount", "userId", "category", "type", "note", "currency", "paymentTime", "withdrawalAccountName", "withdrawalAccountId", "receivingAccountName", "receivingAccountId"}>}
POST http://localhost:8089/api/v3/records/search HTTP/1.1
Accept: application/json
Content-Type: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}

{
  "recordType": "EXPENSE",
  "amountGreaterThan": 100,
  "amountLessThan": 50000,
  "paymentTimeLessThan": "2025-08-01T00:00:00.000Z",
  "paymentTimeGreaterThan": "2024-08-01T00:00:00.000Z",
  "limit": 100,
  "offset": 0
}


### Count user records.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {Number}
POST http://localhost:8089/api/v3/records/count HTTP/1.1
Accept: application/json
Content-Type: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}

{
  "recordType": "INCOME",
  "amountGreaterThan": 100,
  "amountLessThan": 50000,
  "paymentTimeLessThan": "2025-08-01T00:00:00.000Z",
  "paymentTimeGreaterThan": "2024-08-01T00:00:00.000Z"
}

### Get user records report.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response content disposition => Content-Disposition: attachment; filename=records-report.json
# Expected response body => {Array<{"id", "amount", "userId", "category", "type", "note", "currency", "paymentTime", "withdrawalAccountName", "withdrawalAccountId", "receivingAccountName", "receivingAccountId"}>}
POST http://localhost:8089/api/v3/records/report HTTP/1.1
Accept: application/json
Content-Type: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}

{
  "recordType": "INCOME",
  "amountGreaterThan": 100,
  "amountLessThan": 50000,
  "paymentTimeLessThan": "2025-08-01T00:00:00.000Z",
  "paymentTimeGreaterThan": "2024-08-01T00:00:00.000Z"
}


### Get user records.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {Array<{"id", "amount", "userId", "category", "type", "note", "currency", "paymentTime", "withdrawalAccountName", "withdrawalAccountId", "receivingAccountName", "receivingAccountId"}>}
GET http://localhost:8089/api/v3/records HTTP/1.1
Accept: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}


### Add user record.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 201
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "amount", "userId", "category", "type", "note", "currency", "paymentTime", "withdrawalAccountName", "withdrawalAccountId", "receivingAccountName", "receivingAccountId"}}
POST http://localhost:8089/api/v3/records HTTP/1.1
Accept: application/json
Content-Type: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}

{
  "amount": 5000,
  "paymentTime": "2025-07-02T00:00:00.000Z",
  "category": "Rent",
  "type": "EXPENSE",
  "note": "August home rent.",
  "withdrawalAccountId": "d4b4e407-63f5-7646-efe7-548f0ef37a48"
}


### Get user record.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "amount", "userId", "category", "type", "note", "currency", "paymentTime", "withdrawalAccountName", "withdrawalAccountId", "receivingAccountName", "receivingAccountId"}}
GET http://localhost:8089/api/v3/records/0cd12947-223c-4600-987d-5b8dfd9556b9 HTTP/1.1
Accept: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}


### Update user record.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "amount", "userId", "category", "type", "note", "currency", "paymentTime", "withdrawalAccountName", "withdrawalAccountId", "receivingAccountName", "receivingAccountId"}}
PATCH http://localhost:8089/api/v3/records/0cd12947-223c-4600-987d-5b8dfd9556b9 HTTP/1.1
Accept: application/json
Content-Type: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}; XSRF-TOKEN=33203290-caef-4c60-bc24-812cef7c6828
X-XSRF-TOKEN: AjbaL-Ej5pqav4MOAAWTQ5mr0sgTwiObPGjAQlBO1ZZC-wNNMQXoH9IR36q33OJrZiinIK-b_6pw8Be2BFnyITUo4vV0wzF1

{
  "paymentTime": "2025-07-27T00:00:00.000Z",
  "category": "Investment",
  "note": "August investments."
}


### Delete user record.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 204
# Expected response content type => Content-Type: application/json
# Expected response body => Empty
DELETE http://localhost:8089/api/v3/records/0cd12947-223c-4600-987d-5b8dfd9556b9 HTTP/1.1
Accept: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}; XSRF-TOKEN=33203290-caef-4c60-bc24-812cef7c6828
X-XSRF-TOKEN: AjbaL-Ej5pqav4MOAAWTQ5mr0sgTwiObPGjAQlBO1ZZC-wNNMQXoH9IR36q33OJrZiinIK-b_6pw8Be2BFnyITUo4vV0wzF1
