### Get record categories.
GET http://localhost:8089/api/v1/record-categories HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGJ1ZGdldG1hdGUuY29tIiwiaWF0IjoxNzU1MzQxNzY1LCJleHAiOjE3NTUzNTI1NjV9.3fDa48mbKH6jJuC0hgZP-xAegLJVHXXMjiw9Z88rcyk


