### Get user.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "username", "firstname", "lastname", "country", "city", "address", "postalCode", "avatarColor", "role"}}
GET http://localhost:8089/api/v3/users HTTP/1.1
Accept: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}


### Update user.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {{"id", "username", "firstname", "lastname", "country", "city", "address", "postalCode", "avatarColor", "role"}}
PATCH http://localhost:8089/api/v3/users HTTP/1.1
Accept: application/json
Content-Type: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}

{
  "firstname": "T-firstname",
  "lastname": "T-lastname",
  "country": "USA",
  "city": "Los Angeles"
}


### Delete user.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 204
# Expected response content type => Content-Type: application/json
# Expected response body => Empty
DELETE http://localhost:8089/api/v3/users HTTP/1.1
Accept: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}


### Get user notifications.
# @no-redirect
# @no-cookie-jar
# Expected response status => HTTP/1.1 200
# Expected response content type => Content-Type: application/json
# Expected response body => {Array<{ "id", "ownerUsername", "requestedUsername", "accountName" }>}
GET http://localhost:8089/api/v3/users/notifications HTTP/1.1
Accept: application/json
Sec-Fetch-Site: same-site;
Cookie: JSESSIONID={{spring_cookie}}